language: ruby
rvm:
  - 2.0.0
before_install:
  - gem install bundler
before_script:
  - cp config/database.mysql.yml config/database.yml
  - mysql -e 'create database lethal_test;'
script: bundle exec rspec spec
